### ISSUE TITLE
문제집 목록 조회 기능 구현

### ISSUE THREAD

**Issue by skatn** [skatn/remind-me-back#13]
# Todo
- [x] ~~최근 학습한 문제집 10개 조회 기능 구현~~ 프론트에서 구현
- [x] 보유 중인 문제집 무한스크롤 조회 기능 구현
- [x] 문제집 검색 기능 구현
