### ISSUE TITLE
테스트 코드 작성

### ISSUE THREAD

**Issue by skatn** [skatn/remind-me-back#37]
# Todo
- [x] Member 로직 테스트
- [x] Subject 로직 테스트
- [x] Question 로직 테스트
- [x] 문제 풀이 로직 테스트
